[config]
schemaVersion = "0.0.1"

[package]
namespace = "bo0tzz"
name = "PeglinGPS"
versionNumber = "1.2.2"
description = "Plot out your path on the minimap"
websiteUrl = "https://github.com/bo0tzz/PeglinGPS"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.1900"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []